// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package grap

type Direccion struct {
	ID   int    `json:"id"`
	Casa string `json:"casa"`
}

type Group struct {
	ID       int     `json:"id"`
	Title    string  `json:"title"`
	UserID   int     `json:"user_id"`
	CreateAt *string `json:"createAt"`
	CloseAt  *string `json:"closeAt"`
}

type Message struct {
	ID       int     `json:"id"`
	Message  string  `json:"message"`
	UserID   int     `json:"user_id"`
	GroupID  int     `json:"group_id"`
	CreateAt *string `json:"createAt"`
}

type NewDireccion struct {
	Casa string `json:"casa"`
}

type NewMessage struct {
	Message string `json:"message"`
	UserID  int    `json:"user_id"`
	GroupID int    `json:"group_id"`
}

type NewUser struct {
	Name           string  `json:"name"`
	LastName       *string `json:"last_name"`
	Identification string  `json:"identification"`
	Age            *int    `json:"age"`
	Direccion      int     `json:"direccion"`
	Password       *string `json:"password"`
}

type Token struct {
	Token     string `json:"token"`
	ExpiredAt int    `json:"expired_at"`
}

type UpdateDireccion struct {
	ID   int     `json:"id"`
	Casa *string `json:"casa"`
}

type UpdateGroup struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
}

type UpdateUser struct {
	ID             int     `json:"id"`
	Name           string  `json:"name"`
	LastName       *string `json:"last_name"`
	Identification string  `json:"identification"`
	Age            *int    `json:"age"`
}

type User struct {
	ID             int        `json:"id"`
	Password       *string    `json:"password"`
	Rol            string     `json:"rol"`
	Name           string     `json:"name"`
	StatusLog      *bool      `json:"status_log"`
	LastName       *string    `json:"last_name"`
	Identification string     `json:"identification"`
	CreateAt       *string    `json:"createAt"`
	UpdateAt       *string    `json:"updateAt"`
	Age            *int       `json:"age"`
	Direccion      *Direccion `json:"direccion"`
}
